-- Portfolio Studio Database Schema Dump
-- Database: PostgreSQL
-- Generated by Antigravity based on project Prisma structure

-- Drop types if they exist (optional)
-- DROP TYPE IF EXISTS "PublishStatus" CASCADE;

-- Create Enum Type
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'PublishStatus') THEN
        CREATE TYPE "PublishStatus" AS ENUM ('pending', 'approved', 'rejected');
    END IF;
END $$;

-- --------------------------------------------------------
-- Table Structure for "User"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',
    "avatarUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- --------------------------------------------------------
-- Table Structure for "Category"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Category" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

-- --------------------------------------------------------
-- Table Structure for "Template"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Template" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "categoryId" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "placeholders" JSONB NOT NULL,
    "templateImgUrl" TEXT NOT NULL,
    "previewUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Template_pkey" PRIMARY KEY ("id")
);

-- --------------------------------------------------------
-- Table Structure for "UserTemplate"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "UserTemplate" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "templateId" TEXT NOT NULL,
    "filledValues" JSONB NOT NULL,
    "sectionsData" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserTemplate_pkey" PRIMARY KEY ("id")
);

-- --------------------------------------------------------
-- Table Structure for "History"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "History" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "History_pkey" PRIMARY KEY ("id")
);

-- --------------------------------------------------------
-- Table Structure for "UserTemplatePublish"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "UserTemplatePublish" (
    "id" TEXT NOT NULL,
    "userTemplateId" TEXT NOT NULL,
    "domainType" TEXT NOT NULL,
    "domain" TEXT,
    "note" TEXT,
    "status" "PublishStatus" NOT NULL DEFAULT 'pending',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserTemplatePublish_pkey" PRIMARY KEY ("id")
);

-- --------------------------------------------------------
-- Indexes
-- --------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX IF NOT EXISTS "Category_name_key" ON "Category"("name");

-- --------------------------------------------------------
-- Foreign Key Constraints
-- --------------------------------------------------------

-- Template -> Category
ALTER TABLE "Template" 
ADD CONSTRAINT "Template_categoryId_fkey" 
FOREIGN KEY ("categoryId") REFERENCES "Category"("id") 
ON DELETE RESTRICT ON UPDATE CASCADE;

-- UserTemplate -> User
ALTER TABLE "UserTemplate" 
ADD CONSTRAINT "UserTemplate_userId_fkey" 
FOREIGN KEY ("userId") REFERENCES "User"("id") 
ON DELETE RESTRICT ON UPDATE CASCADE;

-- UserTemplate -> Template
ALTER TABLE "UserTemplate" 
ADD CONSTRAINT "UserTemplate_templateId_fkey" 
FOREIGN KEY ("templateId") REFERENCES "Template"("id") 
ON DELETE RESTRICT ON UPDATE CASCADE;

-- History -> User
ALTER TABLE "History" 
ADD CONSTRAINT "History_userId_fkey" 
FOREIGN KEY ("userId") REFERENCES "User"("id") 
ON DELETE RESTRICT ON UPDATE CASCADE;

-- UserTemplatePublish -> UserTemplate
ALTER TABLE "UserTemplatePublish" 
ADD CONSTRAINT "UserTemplatePublish_userTemplateId_fkey" 
FOREIGN KEY ("userTemplateId") REFERENCES "UserTemplate"("id") 
ON DELETE CASCADE ON UPDATE CASCADE;
